micronaut:
  application:
    name: checker
  security:
    token:
      jwt:
        signatures:
          jwks:
            signer:
              url: 'http://localhost:8081/keys'
---
logger:
  levels:
    mn.spike.jwk: DEBUG
