micronaut:
  application:
    name: signer
  server:
    port: 8081
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "pleaseChangeThisSecretForANewOne"
---
config-based-auth:
  enabled: true
  accounts:
    test:
      secret: test
      roles:
        - ROLE1
        - ROLE2
