micronaut:
  application:
    name: signer
  server:
    port: 8081
  security:
    authentication: bearer
---
logger:
  levels:
    mn.spike.jwk: DEBUG
---
config-based-auth:
  enabled: true
  accounts:
    test:
      secret: test
      roles:
        - ROLE1
        - ROLE2
